import http from "node:http";
import path from "path";
import { fileURLToPath } from "url";
import { readFile } from "node:fs/promises";

const root=path.dirname(fileURLToPath(import.meta.url));
const port=Number(process.env.PORT??3000);
const sleeperBase="https://api.sleeper.app/v1";
const sleeperProjectionBase="https://api.sleeper.com/projections/nfl";
const sleeperMarketCache=new Map(),playersCache={data:null,at:0,promise:null},draftCache=new Map(),recommendationCache=new Map();
const BUILD="sleeper-live-refresh-2026-08-31-37";

async function sleeper(pathname){const r=await fetch(`${sleeperBase}${pathname}`,{headers:{"user-agent":"Mozilla/5.0 Sleeper-Draft-Assistant/0.1"}});if(!r.ok)throw new Error(`Sleeper returned ${r.status} · ${await r.text()}`);return r.json()}
async function nflPlayers(){const now=Date.now();if(playersCache.data&&now-playersCache.at<30*60*1000)return playersCache.data;if(playersCache.promise)return playersCache.promise;playersCache.promise=sleeper("/players/nfl").then(data=>{playersCache.data=data;playersCache.at=Date.now();playersCache.promise=null;return data}).catch(e=>{playersCache.promise=null;throw e});return playersCache.promise}
async function sleeperDraft(draftId){const key=String(draftId),cached=draftCache.get(key),now=Date.now();if(cached?.data&&now-cached.at<30*1000)return cached.data;if(cached?.promise)return cached.promise;const promise=sleeper(`/draft/${draftId}`).then(data=>{draftCache.set(key,{data,at:Date.now()});return data}).catch(e=>{draftCache.delete(key);throw e});draftCache.set(key,{promise});return promise}
function nextFor(pickNo,teams,userSlot,type){if(!userSlot)return null;for(let p=pickNo;p<=teams*100;p++){const round=Math.ceil(p/teams),within=((p-1)%teams)+1,sl=type==="linear"?within:(round%2===1?within:teams-within+1);if(sl===userSlot)return p}return null}
function slot(pickNo,teams,type){const within=((pickNo-1)%teams)+1,round=Math.ceil(pickNo/teams);return type==="linear"?within:(round%2===1?within:teams-within+1)}
function fieldName(scoring){return scoring.includes("half")?"adp_half_ppr":scoring.includes("standard")||scoring.includes("std")?"adp_std":"adp_ppr"}
function pointsField(scoring){return scoring.includes("half")?"pts_half_ppr":scoring.includes("standard")||scoring.includes("std")?"pts_std":"pts_ppr"}
async function sleeperMarket(scoring,year){const adpField=fieldName(scoring),ptsField=pointsField(scoring),cacheKey=`sleeper-market-${adpField}-${ptsField}-${year}`,cached=sleeperMarketCache.get(cacheKey);if(cached&&Date.now()-cached.at<30*60*1000)return cached.data;if(cached?.promise)return cached.promise;const promise=fetch(`${sleeperProjectionBase}/${year}?season_type=regular&position[]=QB&position[]=RB&position[]=WR&position[]=TE&position[]=K&position[]=DEF&order_by=${adpField}`,{headers:{"user-agent":"Mozilla/5.0 Sleeper-Draft-Assistant/0.1","accept":"application/json"}}).then(async r=>{if(!r.ok)throw new Error(`Sleeper projections returned ${r.status}`);return r.json()}).then(rows=>{const map=new Map();for(const p of Array.isArray(rows)?rows:[]){const id=String(p.player_id??p.stats?.player_id??""),rawAdp=Number(p[adpField]??p.stats?.[adpField]),rawPts=Number(p[ptsField]??p.stats?.[ptsField]);if(id&&(Number.isFinite(rawAdp)&&rawAdp>0&&rawAdp<999||Number.isFinite(rawPts)&&rawPts>0))map.set(id,{adp:Number.isFinite(rawAdp)&&rawAdp>0&&rawAdp<999?rawAdp:null,points:Number.isFinite(rawPts)&&rawPts>0?rawPts:null})}sleeperMarketCache.set(cacheKey,{at:Date.now(),data:map});return map}).catch(()=>new Map());sleeperMarketCache.set(cacheKey,{promise});return promise}
function positionBaseline(raw,pos,needs,flexSlots){const vals=raw.filter(x=>x.position===pos&&Number.isFinite(x.points)).map(x=>x.points).sort((a,b)=>b-a);if(!vals.length)return null;const starters=needs[pos]??1,flexShare=(pos==="RB"||pos==="WR")?Math.ceil(flexSlots/2):0,replacementIndex=Math.min(vals.length-1,Math.max(0,starters+flexShare+8));return vals[replacementIndex]}
async function recommend(draftId){const draft=await sleeperDraft(draftId),[picks,players]=await Promise.all([sleeper(`/draft/${draftId}/picks`),nflPlayers()]),scoring=String(draft.metadata?.scoring_type??"ppr").toLowerCase(),teams=Number(draft.settings?.teams??12),type=draft.type??"snake",current=Math.max(1,...picks.map(p=>Number(p.pick_no)||0),0)+1,drafted=new Set(picks.map(p=>p.player_id)),userId=process.env.SLEEPER_USER_ID??draft.creators?.[0]??null,userSlot=userId&&draft.draft_order?Number(draft.draft_order[userId]):null,userPick=nextFor(current,teams,userSlot,type),nextUserPick=userPick?nextFor(userPick+1,teams,userSlot,type):null;
const roster={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};for(const p of picks.filter(x=>userSlot&&Number(x.draft_slot)===userSlot)){const pos=p.metadata?.position;if(pos&&Object.hasOwn(roster,pos))roster[pos]++}const needs={QB:Number(draft.settings?.slots_qb??1),RB:Number(draft.settings?.slots_rb??2),WR:Number(draft.settings?.slots_wr??2),TE:Number(draft.settings?.slots_te??1),K:Number(draft.settings?.slots_k??0),DEF:Number(draft.settings?.slots_def??0)},flexSlots=Number(draft.settings?.slots_flex??draft.settings?.slots_wrt??2),market=await sleeperMarket(scoring,draft.season??new Date().getFullYear());
const raw=Object.entries(players).map(([id,pl])=>{if(!pl||drafted.has(id)||pl.status!=="Active"||!pl.team)return null;const pos=pl.position||(Array.isArray(pl.fantasy_positions)?pl.fantasy_positions[0]:"");if(!["QB","RB","WR","TE","K","DEF"].includes(pos))return null;const name=[pl.first_name,pl.last_name].filter(Boolean).join(" ")||pl.full_name||pl.team,data=market.get(String(id));if(!name||!data)return null;if(["K","DEF"].includes(pos)&&data.adp==null&&data.points==null)return null;if(["K","DEF"].includes(pos)&&(needs[pos]??0)<=0)return null;return{id,name,position:pos,team:String(pl.team),adp:data.adp,points:data.points}}).filter(Boolean);
const recentByPosition={QB:0,RB:0,WR:0,TE:0,K:0,DEF:0};for(const p of picks.slice(-10)){const pos=p.metadata?.position;if(pos&&Object.hasOwn(recentByPosition,pos))recentByPosition[pos]++}const round=userPick?Math.ceil(userPick/teams):1,rosterSlots=Object.values(needs).reduce((a,b)=>a+b,0)+flexSlots,filledSlots=Object.values(roster).reduce((a,b)=>a+b,0),picksRemaining=Math.max(0,rosterSlots-filledSlots),baselines={QB:positionBaseline(raw,"QB",needs,flexSlots),RB:positionBaseline(raw,"RB",needs,flexSlots),WR:positionBaseline(raw,"WR",needs,flexSlots),TE:positionBaseline(raw,"TE",needs,flexSlots),K:positionBaseline(raw,"K",needs,0),DEF:positionBaseline(raw,"DEF",needs,0)};
const candidates=raw.map(x=>{const isSpecial=x.position==="K"||x.position==="DEF",rosterCount=roster[x.position]??0,starterNeed=Math.max(0,(needs[x.position]??0)-rosterCount),specialLate=round>=Math.max(11,Math.ceil((rosterSlots-3)/teams)),specialUrgency=isSpecial&&starterNeed>0&&picksRemaining<=Math.max(4,teams*2)&&specialLate,runCount=recentByPosition[x.position]??0,runBonus=starterNeed>0&&runCount>=3?Math.min(12,(runCount-2)*4):0,startingNeed=isSpecial?(specialUrgency?16:0):(starterNeed>0?(round<=3?Math.min(12,starterNeed*4):Math.min(18,starterNeed*6)):0),flexEligible=x.position==="RB"||x.position==="WR",flexNeed=flexEligible&&round<=8&&roster.RB+roster.WR<needs.RB+needs.WR+flexSlots?4:0,surplusPenalty=x.position==="WR"&&roster.WR>=needs.WR+Math.max(0,flexSlots-1)?Math.min(18,6+(roster.WR-(needs.WR+Math.max(0,flexSlots-1)))*6):x.position==="RB"&&roster.RB>=needs.RB+1?8:0,qbDepthPenalty=x.position==="QB"&&roster.QB>=needs.QB?-22:0,teDepthPenalty=x.position==="TE"&&roster.TE>=needs.TE?-10:0,adpVsPick=userPick&&x.adp!=null?userPick-x.adp:0,marketValue=x.adp!=null?(userPick?Math.max(0,Math.min(58,34+adpVsPick*1.15)):Math.max(0,58-x.adp*0.4)):18,reachPenalty=x.adp!=null&&userPick?Math.max(0,-adpVsPick-8)*2.0:0,baseline=baselines[x.position],vor=baseline!=null&&x.points!=null?x.points-baseline:0,projectionValue=x.points!=null?Math.max(0,Math.min(62,30+vor*0.85)):isSpecial?12:0,specialEarlyPenalty=isSpecial&&!specialUrgency?Math.max(0,(12-round)*7):0,score=marketValue+projectionValue+startingNeed+flexNeed+runBonus+qbDepthPenalty+teDepthPenalty-surplusPenalty-reachPenalty-specialEarlyPenalty;return{...x,score,starterNeed,adpVsPick,vor,projectionValue,surplusPenalty,specialUrgency,runCount,runBonus}}).sort((a,b)=>b.score-a.score||b.projectionValue-a.projectionValue||(a.adp??999)-(b.adp??999)||a.name.localeCompare(b.name));
const best=candidates[0]??null,runner=candidates[1]?.score??(best?best.score-8:0),confidence=best?Math.round(Math.min(86,Math.max(58,60+Math.max(0,best.score-runner)*1.35))):null,nextTurnTargets=nextUserPick?[...candidates].filter(x=>x.id!==best?.id).sort((a,b)=>Math.abs((a.adp??999)-nextUserPick)-Math.abs((b.adp??999)-nextUserPick)).slice(0,4).map(x=>({name:x.name,position:x.position,team:x.team,adp:x.adp,points:x.points,survivalPct:x.adp==null?null:x.adp<=nextUserPick?100:Math.max(0,Math.min(100,Math.round(100-(x.adp-nextUserPick)*9)))})):[];
let plan="Take the best combination of projected production, market price, and roster fit; reassess the board after the next turn.";if(best&&nextUserPick){const back=nextTurnTargets.filter(x=>x.survivalPct==null||x.survivalPct>=60).slice(0,2).map(x=>x.name).join(" or ");plan=back?`Take ${best.name} now. At pick ${nextUserPick}, ${back} has a reasonable market chance to remain.`:`Take ${best.name} now. At pick ${nextUserPick}, take the best remaining player rather than forcing a position.`}const available=raw.length,recentPicks=picks.slice(-8).reverse().map(p=>({pickNo:p.pick_no,name:[p.metadata?.first_name,p.metadata?.last_name].filter(Boolean).join(" "),position:p.metadata?.position??"",playerId:p.player_id})),adpLabel=market.size?`Sleeper ${scoring.toUpperCase()} ADP + projections`:"unavailable",balanceNote=best?.surplusPenalty>0?` Your ${best.position} depth is already strong, so this pick needs to clear a higher value bar.`:best?.specialUrgency?` Your ${best.position==='DEF'?'D/ST':best.position} slot is still open, and the draft is late enough to address it.`:best?.runBonus>0?` A recent ${best.position==='DEF'?'D/ST':best.position} run was detected, so the recommendation is protecting against the position drying up.`:"",projectionNote=best?.points!=null?` Projected ${best.points.toFixed(1)} ${scoring.toUpperCase()} points${best.vor!=null&&best.vor!==0?` · +${best.vor.toFixed(1)} vs positional replacement`:""}.`:"";
return{build:BUILD,scoringType:scoring,teams,draftStatus:draft.status,currentPickNo:current,currentSlot:slot(current,teams,type),userSlot,userPickNo:userPick,nextUserPick,picksUntilUser:userPick?userPick-current:null,availableCount:available,roster,needs,rosterSlots,filledSlots,recentPicks,marketSource:adpLabel,adpSource:fieldName(scoring),projectionSource:pointsField(scoring),recommendation:best?{name:best.name,position:best.position,team:best.team,adp:best.adp,points:best.points,vor:best.vor,confidence,nextPick:nextUserPick,survivalPct:nextUserPick&&best.adp!=null?(best.adp<=nextUserPick?100:Math.max(0,Math.min(100,Math.round(100-(best.adp-nextUserPick)*9)))):null,reason:`Sleeper ${scoring.toUpperCase()} ADP ${best.adp==null?"—":best.adp.toFixed(1)} · pick ${userPick??"—"} · ${best.adp==null?"no reliable ADP available":best.adpVsPick>=0?`about ${Math.round(best.adpVsPick)} spots earlier than this pick`:`about ${Math.round(Math.abs(best.adpVsPick))} spots later than this pick`}.${projectionNote} ${best.starterNeed>0?`Fills an immediate ${best.position==='DEF'?'D/ST':best.position} starting need.`:"Roster priority, projected production, and pick value considered."}${balanceNote}`,plan}:null,alternatives:candidates.slice(1,5).map(x=>({name:x.name,position:x.position,team:x.team,adp:x.adp,points:x.points,vor:x.vor,survivalPct:nextUserPick&&x.adp!=null?(x.adp<=nextUserPick?100:Math.max(0,Math.min(100,Math.round(100-(x.adp-nextUserPick)*9)))):null,adpVsPick:userPick&&x.adp!=null?userPick-x.adp:null})),nextTurnTargets,nextPickDistance:userPick&&nextUserPick?nextUserPick-userPick:null}}
async function getRecommendation(draftId){const key=String(draftId),cached=recommendationCache.get(key);if(cached?.data&&cached.pickNo===cached.data.currentPickNo)return cached.data;if(cached?.promise)return cached.promise;const promise=recommend(draftId).then(data=>{recommendationCache.set(key,{data,pickNo:data.currentPickNo});return data}).catch(e=>{recommendationCache.delete(key);throw e});recommendationCache.set(key,{promise});return promise}
function prewarmRecommendation(draftId){const cached=recommendationCache.get(String(draftId));if(cached?.promise)return;getRecommendation(draftId).catch(()=>{})}
async function proxy(pathname,res){try{const data=await sleeper(pathname);res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(data))}catch(e){res.writeHead(502,{"content-type":"application/json"});res.end(JSON.stringify({error:e instanceof Error?e.message:String(e)}))}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url??"/",`http://${req.headers.host??"localhost"}`);if(u.pathname==="/"||u.pathname==="/index.html"){const html=await readFile(path.join(root,"../public/index.html"));res.writeHead(200,{"content-type":"text/html; charset=utf-8","cache-control":"no-store"});res.end(html);return}if(u.pathname==="/api/health"){res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify({ok:true,build:BUILD}));return}const live=u.pathname.match(/^\/api\/live\/(\d+)$/);if(live){const draftId=live[1],[draft,picks]=await Promise.all([sleeperDraft(draftId),sleeper(`/draft/${draftId}/picks`)]);prewarmRecommendation(draftId);res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify({draft,picks}));return}const warm=u.pathname.match(/^\/api\/warm\/(\d+)$/);if(warm){const draft=await sleeperDraft(warm[1]),scoring=String(draft.metadata?.scoring_type??"ppr").toLowerCase();await Promise.all([nflPlayers(),sleeperMarket(scoring,draft.season??new Date().getFullYear())]);prewarmRecommendation(warm[1]);res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify({ok:true,build:BUILD}));return}const m=u.pathname.match(/^\/api\/recommendations\/(\d+)$/);if(m){const data=await getRecommendation(m[1]);res.writeHead(200,{"content-type":"application/json","cache-control":"no-store"});res.end(JSON.stringify(data));return}if(u.pathname.startsWith("/api/sleeper/")){await proxy(u.pathname.slice("/api/sleeper".length),res);return}res.writeHead(404);res.end("Not found")}catch(e){res.writeHead(502,{"content-type":"application/json"});res.end(JSON.stringify({error:e instanceof Error?e.message:String(e)}))}});server.listen(port,"0.0.0.0",()=>console.log(`Sleeper Draft Assistant: http://localhost:${port}`));